# Generated by Django 5.0.4 on 2024-06-01 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0011_alter_error_form_date_log_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id_contact_form', models.AutoField(primary_key=True, serialize=False)),
                ('email_contact', models.EmailField(max_length=254, null=None)),
                ('phone_contact', models.CharField(max_length=15)),
                ('company_contact', models.CharField(max_length=10)),
                ('message_contact', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='error_form',
            name='date_log_error',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 4, 25, 227762, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagetrack',
            name='DateTimeTrack',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 4, 25, 226762, tzinfo=datetime.timezone.utc)),
        ),
    ]
